name: Clan
author:  Tradotto by Emis Founder ItaSkyGames
description: Plugin dei Clan
version: 1.1.8
main: Clans\FactionMain
api: [2.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5 3.0.0, 3.0.1]
commands:
  c:
    description: Usa /c help per la lista dei comandi
    permission: c.command
permissions:
  c.command:
    default: true
    description: "Plugin dei Clan"
